name: on-push-test-and-build-app

on: push

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - name: Setup Go 1.21.0
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'

      - name: Go Test -> Summary
        uses: dmatryx/go-test-summary@v1

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -o go-test-summary-example .
